apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-based-on-snapshot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 50Gi
  dataSource:  # This is the interesting bit.
    name: my-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
